### ISSUE TITLE
Warning: Invalid CRT parameters detected

### ISSUE THREAD

**Issue by AmkCity** [Austinb/GameQ#17] opened 2012-01-12 10:56 UTC
too many this messages
Warning: Invalid CRT parameters detected in C:\xampp\htdocs\amursk-portal.ru\game_stats\GameQ.php on line 771

I scan the list for about 30 local game servers, and query the state of the script, there are many this warnings

sory for my bad english

**Comment by Austinb** [comment] 2012-01-12 16:29
What version of PHP are you running this in?

**Comment by AmkCity** [comment] 2012-01-13 11:51
xampp 1.7.7 instaled
php 5.3.8

**Comment by Austinb** [comment] 2012-01-23 02:02
Hello,

I am still unable to reproduce this warning.  I am using that version of PHP 5 currently to devel on (I havent updated to 5.3.9). Its possible it could be a php.ini setting but I am not sure.  From the error and the positioning it makes me think it is the $error = NULL being defined inline instead of being defined before hand but I am not seeing that warning in my environment.  Also unable to find any specific issue searching the php bug database that would be related to this error.

Any more information you can provide would be of help. Thanks!

**Comment by Austinb** [comment] 2012-02-06 16:54
I have not gotten any feedback this issue.  I am closing the issue.  If you have more information such as your settings in php.ini or any other non-production settings please reopen and let me know.  Also if you solved the issue please post what you did so other users can use that information for reference if they run into a similar issue.

**Closed as completed by Austinb** 2012-02-06 16:54 UTC
Labels: Bug, v2
