### ISSUE TITLE
CoD Black Ops support

### ISSUE THREAD

**Issue by TacTicToe66** [Austinb/GameQ#189] opened 2014-08-20 07:43 UTC
I know this has been asked before. I have the protocol info needed to create the protocol script. I just do not know how to port it to GameQ. Can you add support for this if I send you the info you need? You will need to add a line for the admin to add their rcon password for it to query all the info. 

Please?

**Comment by Austinb** [comment] 2014-08-20 14:16
In order to build this I basically need a running test server with players.  Passing login info is not an issue the problem is testing.

**Comment by TacTicToe66** [comment] 2014-08-20 17:54
I have a pretty active Nuketown server. I will PM you the rcon as long as you dont have to reboot the server or anything. That sort of tends to piss off players.  :)

**Comment by TacTicToe66** [comment] 2014-08-26 01:58
Any news?

**Comment by TacTicToe66** [comment] 2014-08-31 03:54
BUMP???

**Comment by Austinb** [comment] 2015-02-09 00:55
I never received any information to build and test the protocol with.  Closing.

**Closed as completed by Austinb** 2015-02-09 00:55 UTC
Labels: Feature Request, v2
