### ISSUE TITLE
Newly added servers not being queried

### ISSUE THREAD

**Issue by saltyscootertrash** [Austinb/GameQ#583] opened 2021-10-21 17:28 UTC
I had 2 servers on list and recently added 2 more. The original 2 servers query fine but any added servers with new ip:port will not query. If I add a new port to an existing ip that query's it will query fine but not with new ip's with same port number. All game servers are set up Identical and all are using Debian 10 with all the same setups so not sure why 2 older servers query fine but any newly added servers with new ip:port will not. 

I just noticed the previous post had similar issue with tf2 and the 'A' 
I know others having same problem also with there tf2 servers also stopped querying.

Any help with this would be greatly appreciated, thanks.

From debug.php...

GameQ\Exception\Protocol: GameQ\Protocols\Source::processResponse response type 'A' is not valid in /usr/www/mh/public/applications/axenserverlist/sources/GameQ/Protocols/Source.php:207 Stack trace: #0 /usr/www/mh/public/applications/axenserverlist/sources/GameQ/GameQ.php(585): GameQ\Protocols\Source->processResponse() #1 /usr/www/mh/public/applications/axenserverlist/sources/GameQ/GameQ.php(357): GameQ\GameQ->doParseResponse() #2 /usr/www/mh/public/applications/axenserverlist/interface/debug.php(26): GameQ\GameQ->process() #3 {main} Next Exception: GameQ\Protocols\Source::processResponse response type 'A' is not valid in /usr/www/mh/public/applications/axenserverlist/sources/GameQ/GameQ.php:592 Stack trace: #0 /usr/www/mh/public/applications/axenserverlist/sources/GameQ/GameQ.php(357): GameQ\GameQ->doParseResponse() #1 /usr/www/mh/public/applications/axenserverlist/interface/debug.php(26): GameQ\GameQ->process() #2 {main}

**Comment by Austinb** [comment] 2022-02-11 15:41
Appears to be duplicate of #581

**Closed as completed by Austinb** 2022-02-11 15:41 UTC
Labels: Bug, v3
