### ISSUE TITLE
Arma3 on php 8.0 gives a deprecation notice

### ISSUE THREAD

**Issue by silent001** [Austinb/GameQ#589] opened 2022-01-11 10:50 UTC
On PHP 8.0 I get a depreciation notice as follows:

`<b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/public/src/GameQ/Protocols/Arma3.php</b> on line <b>156</b><br />
`

This is referenced  in the php manual [here](https://www.php.net/manual/en/function.hexdec.php) for the hexdec() function in php 7.4 and up `<html>
<body>

Version | Description
-- | --
7.4.0 | Passing invalid characters will now generate a deprecation notice. The result will still be computed as if the invalid characters did not exist.

</body>
</html>` 

A dirty workaround is to put the following line near the top of the file:

`error_reporting(E_ALL ^ E_DEPRECATED);`

Not sure the correct workaround to fix this for all versions of php as the manual does not say much

**Comment by Austinb** [comment] 2022-02-11 15:39
Can you provide a working example of when this notice is thrown? It appears is the the code deciphering the steam_id server info property.   Has this value changed?

**Comment by bumbummen99** [comment] 2022-02-11 21:21
Is this not a duplicate of https://github.com/Austinb/GameQ/issues/546 ?

**Comment by silent001** [comment] 2022-02-12 21:51
I can give you a working Arma 3 server to query. 
```
$IP = ddns.silentmecha.co.za
$PORT = 2302
```

**Comment by bumbummen99** [comment] 2022-02-12 22:12
> I can give you a working Arma 3 server to query.
> 
> ```
> $IP = ddns.silentmecha.co.za
> $PORT = 2302
> ```

Afaik it wont work due to the reason in the liked issue (if you are on PHP >=7.4) and there **will** be issues with DLC since the hashes do change on update and they are outdated here (this was an issue for my ArmA3 server some months ago).

**Closed as completed** 2022-05-22 13:42 UTC
Labels: Bug, v3, Help Wanted
